version: '3.9'
services:
  syncio:
    image: ghcr.io/iamneur0/syncio:private
    environment:
      JWT_SECRET: 'temp-jwt-secret-key'
      ENCRYPTION_KEY: 'temp-encryption-key-32-chars-long'
    user: "1001:1001"
    volumes:
      - ./data:/app/data
    ports:
      - "3000:3000"
      - "4000:4000"
