services:
  syncio:
    # image: ghcr.io/iamneur0/syncio:private
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTANCE: private
    container_name: syncio
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"
    environment:
      JWT_SECRET: ${JWT_SECRET:-jwt-secret-key}
      ENCRYPTION_KEY: ${ENCRYPTION_KEY:-encryption-key}
      REDIS_URL: redis://syncio_redis:6379
      DATABASE_URL: file:/app/data/sqlite.db
    ports:
      - "3000:3000"
      - "4000:4000"
    depends_on:
      syncio_redis:
        condition: service_healthy
    volumes:
      - ./syncio/data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s


  # Redis (for session storage and caching)
  syncio_redis:
    image: redis:7-alpine
    container_name: syncio_redis
    restart: unless-stopped
    volumes:
      - ./syncio/redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  syncio_data:
    driver: local
  syncio_redis_data:
    driver: local