name: Cleanup Old Images

on:
  schedule:
    # Run every Sunday at 2 AM UTC
    - cron: '0 2 * * 0'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      packages: write

    steps:
    - name: Delete old beta images
      uses: actions/delete-package-versions@v4
      with:
        package-name: ${{ env.IMAGE_NAME }}
        package-type: 'container'
        min-versions-to-keep: 5
        delete-only-untagged-versions: 'true'
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Clean up old main branch images
      run: |
        echo "Cleaning up old main branch images..."
        # Keep only the last 10 main branch images
        # This is handled by the delete-package-versions action above
